### ISSUE TITLE
classification_cnn_vgg16   cann't   run, two  file  don't  exist, x_gtzan_npy.npy

### ISSUE THREAD

**Issue by zhangscofield** [NazarPonochevnyi/Trained-CNN-for-Genre-classification#1]
Can you please add？I want to learn.

**Comment by zhangscofield** [comment]
sorry.  I find.  I  can do  it .

**Comment by NazarPonochevnyi** [comment]
Yeah. These are large files, so I didn't add them to the repository. You can easily create them!
Follow these steps:
1. Download the GTZAN dataset here: http://opihi.cs.uvic.ca/sound/genres.tar.gz
2. Paste files from archive to ./gtzan/ folder
3. Open classification_cnn_vgg16 and delete # in these strings:
```
    # X, y = read_data(gtzan_dir, genres, song_samples, to_melspectrogram, debug=True)
    # np.save('./data/x_gtzan_npy.npy', X)
    # np.save('./data/y_gtzan_npy.npy', y)
```
4. Run classification_cnn_vgg16
5. Files will be create in ./data/ folder

**Comment by NazarPonochevnyi** [comment]
I think the issue can be closed :)
