### ISSUE TITLE
Error while executing the script

### ISSUE THREAD

**Issue by KartikayKumar02** [NazarPonochevnyi/Trained-CNN-for-Genre-classification#2]
The model works fine but while executing the script an error pops up: OSError: Unable to open file (file signature not found). I think the hdf5 file maybe corrupted in this case.

**Comment by NazarPonochevnyi** [comment]
Good afternoon! 
Nowadays we stored weights using Git LFS, so it can be corrupted while downloading. 
Thus, you can download .h5 file and place it manually to ./weights/ directory using this <a href="https://drive.google.com/file/d/1rJEw1N--pgX4w40yQfsuqYiD8lTR3Hz4/view?usp=sharing" target="_blank">link</a>.

**Comment by KartikayKumar02** [comment]
Yes , It works now!
