### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by 1ycx** [NazarPonochevnyi/Trained-CNN-for-Genre-classification#3]
Can you please specify the requirements of different library versions you use ?
If possible, in a `requirements.txt` file like normal using `pip freeze > requirements.txt`.
Thanks.

**Comment by NazarPonochevnyi** [comment]
Okey! We will add it as soon as possible.

**Comment by NazarPonochevnyi** [comment]
I've added [requirements](https://github.com/NazarPonochevnyi/Trained-CNN-for-Genre-classification/blob/master/requirements.txt).

**Comment by sohrabkhanbadr** [comment]
hello my friends, i change "~=" operator in [requirements](https://github.com/NazarPonochevnyi/Trained-CNN-for-Genre-classification/blob/master/requirements.txt) with "==" But overall, it doesn't help much.
I ran the jupyter file but I have a problem with the Python file

**Comment by NazarPonochevnyi** [comment]
Hi!
Could you describe more about the problem, please?
For example, information about your operating system, error messages, and/or screenshots?

**Comment by sohrabkhanbadr** [comment]
Oh, it's my fault, I ran the code again and this time I succeeded in running the code. I will attach the photo for you.
[python predict_vgg16.py](https://pasteboard.co/Jam9oQC.png)
![image](https://user-images.githubusercontent.com/65416303/83067162-67232700-a07b-11ea-8517-fa34629a2979.png)
and this is my pip list
[pip list](https://pasteboard.co/Jamf0Xc.png)

**Comment by NazarPonochevnyi** [comment]
Great! I assume, that we can close this issue :)
