### ISSUE TITLE
The difference between this repository and the mentioned repository

### ISSUE THREAD

**Issue by sohrabkhanbadr** [NazarPonochevnyi/Trained-CNN-for-Genre-classification#4]
Hello . I have a question.
What is the difference between this repository and the [Hguimaraes/gtzan.keras](https://github.com/Hguimaraes/gtzan.keras) repository ?
I noticed higher percentages in the confusion matrix and three input channels.
Other than that, did I miss something that was very special?

**Comment by NazarPonochevnyi** [comment]
Hi!
This repository is the same as the old version of the Hguimaraes/gtzan.keras repository. I added only one thing: the trained weights of vgg model.

But now Hguimaraes updated his repository. I didn't check his changes and didn't apply the new version in this repository.

**Comment by sohrabkhanbadr** [comment]
Hello. Thank you so much.
