### ISSUE TITLE
Maybe leakage in your method of splitting dataset

### ISSUE THREAD

**Issue by woshikafei** [NazarPonochevnyi/Trained-CNN-for-Genre-classification#5]
You have overlap 50% in your data augment, and split a song into several fragments while they were splitted into both train and validation datasets. Besides, VGG16 would have a large Receptive Field. So, maybe your validation dataset have seem itself when training.

**Comment by NazarPonochevnyi** [comment]
Yeah, it can be that two different images in train and test datasets can have 50% of a similar view. I agree that is not the correct way to calculate accuracy on the test dataset. Unfortunately, we are forced to resort to this method due to small size of the GTZAN dataset.

**Comment by woshikafei** [comment]
> Yeah, it can be that two different images in train and test datasets can have 50% of a similar view. I agree that is not the correct way to calculate accuracy on the test dataset. Unfortunately, we are forced to resort to this method due to small size of the GTZAN dataset.

got it! Not a precise score but a good method! Thanks.

**Comment by NazarPonochevnyi** [comment]
Your welcome!
